[package]
name = "rustbook"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]
exclude = ["crates/hello_world", "crates/add"]

[dependencies]

[lib]
name = "rustbook"
path = "env.rs"